Name:           perl-Moose
Version:        0.13
Release:        1%{?dist}
Summary:        Complete modern object system for Perl 5
License:        GPL or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Moose/
Source0:        http://www.cpan.org/authors/id/S/ST/STEVAN/Moose-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch

BuildRequires:  perl(Class::MOP) >= 0.34
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Sub::Exporter) >= 0.954
BuildRequires:  perl(Sub::Install) >= 0.92
BuildRequires:  perl(Sub::Name) >= 0.02
BuildRequires:  perl(Test::Exception) >= 0.21
BuildRequires:  perl(Test::LongString)
BuildRequires:  perl(UNIVERSAL::require) >= 0.10
# optional test #1 (in no particular order)
BuildRequires:  perl(Test::Pod), perl(Test::Pod::Coverage)
# optional test #2
BuildRequires:  perl(DBM::Deep) >= 0.983, perl(DateTime::Format::MySQL)
# optional test #3
BuildRequires:  perl(HTTP::Headers), perl(Params::Coerce), perl(URI)
# optional test #4
# commented out as Locale::US's license is ambiguous at the moment, precluding
# packaging it.
#BuildRequires:  perl(Regexp::Common), perl(Locale::US)

# cpanspec autogenerated requires...
#Requires:       perl(Class::MOP) >= 0.34
#Requires:       perl(Sub::Exporter) >= 0.954
#Requires:       perl(Sub::Install) >= 0.92
#Requires:       perl(Sub::Name) >= 0.02
#Requires:       perl(UNIVERSAL::require) >= 0.10

Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Moose is an extension of the Perl 5 object system.

%prep
%setup -q -n Moose-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Oct 03 2006 Chris Weyl <cweyl@alumni.drew.edu> 0.13-1
- update to 0.13

* Fri Sep 08 2006 Chris Weyl <cweyl@alumni.drew.edu> 0.12-2
- bump

* Sat Sep 02 2006 Chris Weyl <cweyl@alumni.drew.edu> 0.12-1
- Specfile autogenerated by cpanspec 1.69.1.
